bla = input('óla pai, quem você mais ama de nossa casa?')
print('certo')
niu = input('eu percebi que você qué o maximo pra com que eu faça as coisas em que você pede, Certo?')
print('então...')
print('as pessoas em que você gosta são' ,bla, 'e os outros.  Certo?')
print('Obrigado por fazer este meu teste, eu te amo pai :)')
